/**
 * Writes dist/_headers after a build.
 *
 * The CSP allow-lists inline scripts by sha256, and Astro's hashes change
 * whenever a component script changes — so this is generated from the actual
 * build output rather than hand-maintained. A stale hand-written hash would
 * silently break the theme toggle and the lightbox in production.
 *
 * Runs automatically via the `postbuild` script.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const dist = join(dirname(fileURLToPath(import.meta.url)), "..", "dist");

const htmlFiles = [];
(function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p);
    else if (entry.endsWith(".html")) htmlFiles.push(p);
  }
})(dist);

const hashes = new Set();
for (const file of htmlFiles) {
  const html = readFileSync(file, "utf8");
  for (const [, body] of html.matchAll(
    /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g
  )) {
    hashes.add(
      `'sha256-${createHash("sha256").update(body).digest("base64")}'`
    );
  }
}

const csp = [
  "default-src 'self'",
  "base-uri 'none'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'none'",
  "img-src 'self' data:",
  "font-src 'self'",
  // Inline style attributes carry the per-section accent (--section-accent),
  // 35 of them. Hashing attributes isn't possible, so this stays 'unsafe-inline'
  // — the practical risk on a static page with no user input is negligible.
  "style-src 'self' 'unsafe-inline'",
  `script-src 'self' ${[...hashes].sort().join(" ")}`,
  "connect-src 'self'",
  "upgrade-insecure-requests",
].join("; ");

const headers = `# Generated by scripts/build-headers.mjs — do not edit by hand.
# Script hashes are derived from the built output on every build.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
`;

writeFileSync(join(dist, "_headers"), headers);
console.log(`dist/_headers written — ${hashes.size} script hash(es) allow-listed`);
